### ISSUE TITLE
old modules support in v2? certificate transparency, shodan, censys...

### ISSUE THREAD

**Issue by juju4** [Netflix/Scumblr#112]
Hello,

with v2, are those modules unsupported (tagged legacy) or any plan to migrate them?
https://github.com/Netflix/Scumblr/blob/a7c09832ca8eb409ec7e04873baa60895437650d/lib/search_providers/ct.rb
https://github.com/davidlebr1/ScumblrProviders

Thanks

**Comment by ahoernecke** [comment]
Hi, we are continuing to support the legacy search providers. The shodan and censys ones you pointed to I had never seen before and were not merged into the main repo. Since it was developed by someone else and they haven't asked, I'm not going to take merge their code into the main repo. 

The ct search provider is still part of the Scumblr 2 repo. If you're having issues with it, please open a ticket with the issue you're having and we'll take a look.
