### ISSUE TITLE
Issue with Scumblr Results and display ribbon

### ISSUE THREAD

**Issue by mars01** [Netflix/Scumblr#138]
Hi,

I'm running into an issue with Scumblr not showing any results after I run a search on all of my indicators and my Job Status tab is no longer under the Filters sub-tab that it was initially under when I first installed it. The zero appeared after a reboot.

![image](https://cloud.githubusercontent.com/assets/22796280/21775323/9933ec1a-d663-11e6-9056-3169b18a5510.png)

**Comment by ahoernecke** [comment]
Hi @espressobeanie,

You're just talking about the nav bar at the top? It looks like the job status is dropping down because your window is too small to fit it all on the right. I'll take a look at the responsive behavior and fix that.

In the meantime, if you can make your window wider it should show up. Or if you make it narrower eventually you'll get a "hamburger" menu which, if you click it, will have to task/job status section.

**Comment by espressobeanie** [comment]
Hi Andrew,

Yep. The opposite appears to be happening. I have a smaller monitor with 1920x1080 resolution, but my larger monitor has a 1680x1050 and from what I'm seeing, the smaller monitor has no issue at all, but when I move the same window to the larger monitor, that's when the "hamburger" menu appears. I didn't pick up on the issue being a problem with the screen resolution until you mentioned it.

**Comment by ahoernecke** [comment]
Hi @mars01, 

I believe I have included a fix for this in the last commit. There was a range of width for which the hamburger menu wouldn't appear, but the menu bar was too wide to fit. I adjusted the breakpoints and at least on my systems it seems to be behaving better. See if things look better for you too.

**Comment by mars01** [comment]
Hi Andrew,

Thanks. I'll take a look and confirm.

**Comment by sbehrens** [comment]
Hi @mars01,

Please reopen the issue if you are seeing the same problem after updating to the latest commit.

Thanks,
Scott
