### ISSUE TITLE
Google - Search Results Limit

### ISSUE THREAD

**Issue by gosirys** [Netflix/Scumblr#19]
Hello. At the moment I can only get 10 results per search with google. How can i get more results?

**Comment by lazaroskyr** [comment]
I confirm that I am having the same issue. Did anyone find a solution to that?

**Comment by bprodoehl** [comment]
Yeah, the simple change I noted above is enough to get it to pull 100 results rather than just 10. If you're still seeing something less than 100 results per search, even with the change above, there can be a few reasons for this. The search results can include Unicode characters, but MySQL won't accept that by default, so make sure your MySQL database and the scumblr tables are set up to support UTF-8 character encoding. The URL returned can also exceed the string length specified in the database schema. If it hits any of these problems, it just errors out and gives up on the rest of the results it got back from Google. I have a similar small change to have it continue on past results that it encounters errors on. I can look for that and paste it here if you're interested.

**Comment by lazaroskyr** [comment]
So, it is not something that I did wrong, it is working by default like that. 
Shame, this is a great tool nonetheless, but it is a shame that it can return 100 results only. 
Also, a UTF-8 character support is standard for databases, isn't it?

I think that any help that you can offer will be good, not for me only but for others as well.

**Comment by bprodoehl** [comment]
Oh, sorry for the confusion. Scumblr as it is in the repo will only return a max of ten results per search. The loop goes from 1 to 100 in steps of 100, so it will only hit the google search API once, and google's search API returns a max of ten results at a time. If you change the code as I've done above, it steps in increments of 10, so you should actually get close to 100 results. If you've got the time to go through all tue results, and the google search API credits, you could change it from 1..100 to whatever you want, but keep stepping by 10. And no, MySQL still defaults to the latin charset for some incomprehensible reason.

**Comment by lazaroskyr** [comment]
Great answer, thanks. So, we can just change the code and get a bigger set of results.

**Comment by ahoernecke** [comment]
I will roll in a fix for this next time I push an update.

**Comment by lazaroskyr** [comment]
I think is needed. Cheers.

**Comment by ahoernecke** [comment]
This has been fixed in the latest commit.
