### ISSUE TITLE
Enhancement request - check old results

### ISSUE THREAD

**Issue by tomhammond** [Netflix/Scumblr#26]
We recently found that an old result which was previously address later re-appeared as a new result. It'd be great to have Scumblr check all of the old/closed results to ensure that they are no longer online. You could maybe even go a step further and check the currently open results as well.

**Comment by ahoernecke** [comment]
Hi @tomhammond, 

If I understand what you're trying to do correctly, you may be able to put this in as a custom search provider. Basically instead of doing an external search, you would just have it look through your existing closed records, test whether they are back online, and if so modify them in some way (Change status to reopened, add a tag, etc.)

Thoughts?

**Comment by tomhammond** [comment]
That actually seems like a great idea. Let me give that a try!
