### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by anshumanbh** [Netflix/Scumblr#31]
Hi Andy,

I have Scumblr up and running. I have a couple of searches defined and a filter saved as well. I have also added a subscriber (my email) to that saved filter. 

In the production.rb file, I have made the following changes:
Rails.application.routes.default_url_options[:host] = "AWS_public_ip:3000"
Rails.application.routes.default_url_options[:protocol] = "http"

config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
  address:              'smtp.gmail.com',
  port:                 587,
  user_name:            'recipient@gmail.com',
  password:             'password',
  authentication:       'plain',
  enable_starttls_auto: true  }

I then restarted Scumblr and ran "rake send_email_updates" as well. But, I am still not getting any email notifications. 

Any idea why?

Thanks,
Anshuman

**Comment by ahoernecke** [comment]
Hi Anshuman,

I'm assuming you have some (new) results matching the filter when you run the rake task? The notification won't be send out if there are no matching results. 

Are you seeing anything in your logs when you run the rake task?

Thanks

**Comment by ahoernecke** [comment]
I think that all looks right and I don't think you've missed any settings. You may want to close out any browsers connected to scumblr (to minimize traffic to the app), tail -f the logs and run the rake task so you can see what happens when it tries to run. 

One other note... When you run the rake task, a "Summary" entry will be created that basically records the timestamp of when notifications were sent out. The next time you run the task only results created after the summary timestamp will be included. So, if for whatever reason, you had run the email updates and it failed (wasn't configured properly, security group was blocking outbound traffic, etc.), rerunning won't cause another email to go out until new results are added that match the search. You could get around this by running `Summary.delete_all` in the console to make so that it's like no notifications have been sent out.

**Comment by ahoernecke** [comment]
Hi @anshumanbh, Were you able to make any progress on this?

Thanks

**Comment by anshumanbh** [comment]
Hi @ahoernecke I haven't had a chance to look into this since my last message. I got pulled into different things. If you want, you can close this issue for now. If and when I get a chance to look into the email notifications in the future again, I will comment here again and let you know what the status is. Thanks for   following up on this Andy! Cheers

**Comment by ahoernecke** [comment]
Perfect, thanks. Let me know if you're still having issues when you circle back.

**Comment by enasda** [comment]
I have the same issue and still don't receive email notifications.

**Comment by ahoernecke** [comment]
Hi @ensada,

Please open a new issue with the steps you've taken and any entries you have your logs that might be relevant.

Thanks!
