### ISSUE TITLE
adding "search name" column to the results tab

### ISSUE THREAD

**Issue by tDorosheff** [Netflix/Scumblr#55]
Im trying to add a column providing the search name of the individual results shown on the results tab. I found the /scumblr/app/views/results/ _results_table.html.erb, and modified a line in the table head section on lines 2-15, to be this: "<th><%= sort_link @q, :search_name%></th>". Doing this gave me a new column in the results tab titled "search name". The column was populated by the domain of the result, and nothing else. I tried to add a line in the subsequent table body section, lines 16-49, but that was done on a hope and a prayer, as that section looks pretty complicated. Out of sheer curiosity and minimal expectations, I ended up adding the line:
"<td><%= search.name %></td>, but this of course broke the html and gave me an undefined local variable error. After poking around in /scumblr/app/views/searches, i found some files that seem to characterize the correct variable name for the "search name" attribute, which is where i got the syntax "search.name". Would love to get this working, because when analyzing results, it would be nice to know which search provided which result. I suppose this can be gleaned from the context of the result itself, but sort and filter functionality would be nice to have.

**Comment by ahoernecke** [comment]
Hi @tDorosheff,

I can probably help you customize the view for this, but there is a minor detail that you'll need to think through... By design, results can be found by more than one search (so just as a contrived example, maybe you find a tweet by searching google for "scumblr" and then find the same page when you search twitter for "scumblr"). 

In other words, the association between results and searches is one to many... So, in these cases (where there are multiple searches that have found the same result) what do you want to display in the table? The first search that found the result, the most recent, all of them (which could get messy obviously), something else entirely "Found by multiple searches"?

That said, assuming you just want the first search name, I think you'd want to do something like this: (instead of "search.name")

```
@result.search_results.try(:first).try(:search).try(:name)
```

This should look up the first search result, and give you the name of that search.

**Comment by tDorosheff** [comment]
I hadn't considered that outcome, however I am only using google searches that query specific sites (site:pastebin "term", or site:twitter "term"), so do you think i will still run into that problem?

And after inserting that line in the <tbody> section, i got an undefined method `search_name' error.

**Comment by ahoernecke** [comment]
That would be from this other line you added: 
```
<%= sort_link @q, :search_name%>
```

You should be able to replace that with a simple string:
```
Search Name
```
and it will give you a (non-sortable) heading. If you need it to be sortable, that would require a little more effort since that field is on a different model and the helpers don't support sorting that way.

**Comment by ahoernecke** [comment]
As far as your other question, you may not run into that issue, but with the code I provided, if you do it will just show the first search to find the result. So as long as you're ok with that, I think this should work ok.

**Comment by tDorosheff** [comment]
so should by <tbody> line look like this:

<td><%=@result.search_results.try(:first).try(:search).try(:name)%></td>

**Comment by ahoernecke** [comment]
Sorry actually it should be like this:
```
<%= result.search_results.try(:first).try(:search).try(:name)%>
```

**Comment by tDorosheff** [comment]
beautiful, works perfectly. Thanks!

**Comment by ahoernecke** [comment]
No problem!
