### ISSUE TITLE
Deleted Results Are Returned Next Search

### ISSUE THREAD

**Issue by jwilczek** [Netflix/Scumblr#70]
I've noticed that when I delete results (that are not of interest) the next time the search executes all of the results that I just deleted are returned as new results again.

Maybe this is a misunderstanding of how Scumblr works.  Should repeated results get returned after a delete?  Is there a way where I can remove unwanted results and not have them reappear with the next search?

**Comment by ahoernecke** [comment]
Hi @jwilczek,

This would be expected behavior. Search providers look for results and add them to the database if they don't already exist. So if you delete them they will just be added against since they don't exist anymore.

Usually the best way to deal with unwanted results is to set them to a closed status (you can create a specific status like "False positive" or "Not interesting" if you want so you can track how many irrelevant results are being returned by search search provider).

This way the results won't show up in the default search (unless you have checked "Include closed results") and they won't reappear when the search provider is rerun.

If this doesn't work for you reopen the issue, let me know what's missing, and I'll see if I can assist further.

**Comment by jwilczek** [comment]
Thanks!  I thought that may be the case.
