### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by fmonster** [Netflix/Scumblr#96]
Hello, I am new with Scumblr and with Ruby too but I'm trying to run /Scumblr$ rake send_email_updates and I'm getting these erros:
```
rake aborted!
NameError: undefined local variable or method `sync_all' for main:Object
/home/user/Scumblr/config/environments/development.rb:76:in `<top (required)>'
/home/user/Scumblr/config/environment.rb:20:in `<top (required)>'
Tasks: TOP => send_email_updates => environment
(See full trace by running task with --trace)
```
this is my configuration for email in config/environments/production.rb
```
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.default_url_options = { :host => "localhost:3000", :protocol => 'https' }
  config.action_mailer.default_options = {from: 'scumblr@domain.com'}


  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
  address: 'smtp.domain.com',
  port: 465,
  user_name: 'example@domain.com',
  password: 'password',
  authentication: 'plain',
  enable_starttls_auto: true }
```
and I write this to config/environments/development.rb as I see in https://github.com/Netflix/Scumblr/issues/92
```
RAILS_ENV=development rake sync_all
RAILS_ENV=development rake send_email_updates
```
Sorry for my english :(

**Comment by ahoernecke** [comment]
Hello @fmonster,

I think you may have misunderstood the recommendations from that issue. These lines that you referenced from #92:

```
RAILS_ENV=development rake sync_all
RAILS_ENV=development rake send_email_updates
```

Are the shell commands that you need to run to have the Searches run and email updates sent out. You need to remove these from development.rb because they're causing the error you're seeing.

Before you go to run the commands, you also need to add your email configuration options (the ones you put into production.rb) into the development.rb, assuming your rails server is running in development mode.

**Comment by fmonster** [comment]
Oh haha 
I tried but I'm still not receiving any email. Do you have any ideias what I can do? You can ask me questions too incase I made something wrong haha

**Comment by ahoernecke** [comment]
So looking through this, it looks like your first attempt failed because it couldn't contact the smtp server (not sure what would have caused this unless it was not configured correctly or you/your email provider was having a network issue). The second attempt seems like it should have worked. 

If you're only running the send_email_updates tasks, it probably won't send anything. You'll need to make sure that a result matching the saved filter you've subscribed to has been added between tests. The notification will only send if a new result matching the filter was created since the last time you run the send_email_updates task. 

Please do the following:

1. Make sure you have a saved filter setup and that you have subscribed to it.
2. Add a result (by running a search, etc.) that matches you saved filter
3. Run the send_email_updates task

**Comment by ahoernecke** [comment]
Closing due to no response.
